### ISSUE TITLE
Temporary Design 

### ISSUE THREAD

**Issue by EnglishLanguageLearning** [angel5644/EngishLanguajeLearning#2]
Add Logo to home page.
Add Motto to home page.
Add Motto to home page. ( Discite - Vivet - Esse )

**Comment by angel5644** [comment]
Wowowowo

**Comment by angel5644** [comment]
Where should the motto be added? @EnglishLanguageLearning

**Comment by EnglishLanguageLearning** [comment]
At the top and footer I'd say

**Comment by EnglishLanguageLearning** [comment]
Top near the footer

**Comment by EnglishLanguageLearning** [comment]
I mean top opposite the logo

**Comment by angel5644** [comment]
Not knowing where to place it.

**Comment by angel5644** [comment]
Preview

![image](https://user-images.githubusercontent.com/4211541/33808007-dc2b529e-dda4-11e7-8355-72cd45b0316e.png)

**Comment by EnglishLanguageLearning** [comment]
I dont know what else to say , i need another demo.. jaja
