### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by EnglishLanguageLearning** [angel5644/EngishLanguajeLearning#5]
Add text to homepage

Bienvenido English Made Easy! (Blue Buttons) Estudiantes > Padres > Maestros (links to pages with users) Filosofía ELL Simplicidad y Facilidad. Nuestras clases son personalizadas, a tu ritmo, y con un máximo de 6 alumnos por clase. Tema por tema y paso por paso, tu aprendizaje está garantizado. Nuestro enfoque está en el entendimiento real del idioma para desarrollar habilidades lectoras y de escritura. Vocabulario y conversaciones son habilidades que se practican en cada clase.
Cursos en Línea
English Language Learning ofrece cursos 100% en línea disponibles para todos los niveles.

Material Gratis
Encuentra aquí material para el aprendizaje de inglés. Adicionalmente contamos con material para maestros de inglés. Todo el material en esta sección es gratuito.

**Comment by angel5644** [comment]
Looking like this @EnglishLanguageLearning 

![image](https://user-images.githubusercontent.com/4211541/35187822-f239e206-fdef-11e7-8872-5a96bef4f9a8.png)

**Comment by angel5644** [comment]
If you need any arrangement of the elemements or any extra change, let me know. @EnglishLanguageLearning
