### ISSUE TITLE
Website Pages

### ISSUE THREAD

**Issue by EnglishLanguageLearning** [angel5644/EngishLanguajeLearning#6]
Home
Courses
Resources

Hidden Pages (App Pages)
Admin
Students
Finance
Payments

**Comment by angel5644** [comment]
No contact page? @EnglishLanguageLearning

**Comment by angel5644** [comment]
Looking like this. I would include the contact page.

![image](https://user-images.githubusercontent.com/4211541/35187830-3597f646-fdf0-11e7-8c81-6866ce9b6473.png)

**Comment by EnglishLanguageLearning** [comment]
We already had a contacts page! haha don't delete the ones we had!

**Comment by angel5644** [comment]
Alright! Its just hidden
